blank_issues_enabled: false
contact_links:
  - name: Issue Tracker
    url: https://gitlab.com/platynum/certification-authority/container/-/issues/new
    about: Please report bugs, feature requests, and security vulnerabilities here.
