= Container

This projects builds and provides a container for the Certification
Authority (https://gitlab.com/platynum/certification-authority).

include::partial$images.adoc[]

== Configuration

include::partial$environment.adoc[]

== Start container

Start the certification authority container and expose HTTP(S) ports:

[source,bash]
----
$ IMAGE=registry.gitlab.com/platynum/certification-authority-docker:latest
$ docker run -n ca -e NODE_RED_CREDENTIAL_SECRET=password -p 80:80 -p 443:443 $IMAGE
----

== Stop container

Stop the container using the following docker command:

[source,bash]
----
$ docker stop ca
----

== Access the container

The user interface of the container is available via TCP port 443.
Direct your favorite web browser to: `https://localhost/` to use
the user interface (UI).

== Create PKCS12/PFX container

The user interface (UI) of the CA is protected via Client Certificate
Authentication (CCA). The key/certificate is generated automatically
during startup. To generate a PKCS12/PFX container you have to combine
the generated files with the following shell commands inside the
container:

[source,bash]
----
$ CAFILE=$(mktemp)
$ cat Admin/*/ca.crt.pem Sub/*/ca.crt.pem Root/*/ca.crt.pem >${CAFILE}
$ openssl pkcs12 -in Admin/??[a-f1-9]*.crt.pem -inkey Admin/??[a-f1-9]*.priv.key.pem -export -out Admin.pfx -chain -CAfile ${CAFILE} -password pass:password
----

Import the generated PFX container into your browser.

## Import PKCS12/PFX container

Import this container into the certificate store:

.Windows Powershell
[source,powershell]
----
PS C:\>$mypwd = Get-Credential -UserName 'Enter password below' -Message 'Enter password below'
PS C:\>Import-PfxCertificate -FilePath C:\Admin.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $mypwd.Password
----

