== Container

`CONTAINER_ENABLE_APACHE`::
  start Apache httpd 2 in front of Node-RED, set this to `false` to disable
  the built in reverse proxy and authentication, by default this value
  is unset.
`CONTAINER_ENABLE_FLOWS`::
  by default all flows are enabled and started, you can select a subset
  of flows, by using a regex here, e.g.: `OCSP|CRL`.

== Apache httpd

`APACHE_ENABLE_RSA`::
  disable RSA TLS certificate usage, when specified as `false`. By default RSA
  certificate is used. See `HTTPS_CERTIFICATE_ALGORITHM` how to suppress RSA
  certificate generation, too.
`APACHE_ENABLE_EC`::
  disable EC TLS certificate usage, when specified as `false`. By default EC
  certificate is used. See `HTTPS_CERTIFICATE_ALGORITHM` how to suppress EC
  certificate generation, too.
`APACHE_OCSP_STAPLING`::
  enable OCSP stapling within apache httpd reverse proxy using the
  `SSLUseStapling` configuration option, when specified as `true`. By default
  OCSP stapling is disabled.

TIP: You might want to enable `HTTPS_TLS_STATUS_REQUEST` x509v3 extension
within the https certificates, too.

== Node-RED

Consult the
https://nodered.org/docs/user-guide/runtime/configuration[documentation of
Node-RED] for all possible configuration options. Some of them have been mapped
to environment variables.

The following configuration items in `/data/settings.js` can be configured
using environment variables:

`NODE_RED_CREDENTIAL_SECRET`::
  this setting has **no default** (sets `credentialSecret`)
`NODE_RED_LOGGING_CONSOLE_LEVEL`::
  defaults to `info` (sets `logging.console.level`)
`NODE_RED_HTTP_ADMIN_ROOT`::
  defaults to `/admin` (sets `httpAdminRoot`)
`NODE_RED_DISABLE_EDITOR`::
  defaults to `true` (sets `disableEditor`)

The following settings should not be changed, unless you know what your are
doing, otherwise the Apache reverse proxy might not function correctly!

`NODE_RED_UI_HOST`::
  defaults to `127.0.0.1` (sets `uiHost`)
`NODE_RED_UI_PORT`::
  defaults to `1880` (sets `uiPort`)
`NODE_RED_ENABLE_PROJECTS`::
  defaults to `false` (sets `editorTheme.projects.enabled`)

The https://nodered.org/docs/getting-started/docker[page of Node-RED's docker
container] contains additional information about the base image for this
container.

